### ISSUE TITLE
Lack of color options causes poor readability when Freeplane is using a dark theme

### ISSUE THREAD

**Issue by sgjohnson1981** [EdoFro/Freeplane_groovyConsole#7]
The blue colored keywords don't show up very well against a dark background. I was using Atom One Dark Contrast theme and so had to switch to something else in order to see everything.

**Comment by EdoFro** [comment]
You're right. I hadn't noted this before. I thought the console wasn't affected by Freeplane's themes.
I'm going to look at this.

Thanks for reporting,

edo

**Comment by EdoFro** [comment]
@sgjohnson1981,

Ok I released a [new version](https://github.com/EdoFro/Freeplane_groovyConsole/releases/tag/v0.0.8).
The input area is set to "not Dark" colors so the keywords don't loose visibility.

![image](https://github.com/EdoFro/Freeplane_groovyConsole/assets/35700575/37db6699-1339-4d6f-a7ae-dc673a6f719a)

To change the keywords colors was way more difficult, sorry.

BR

edo
